name: Cleanup Deployments

on:
  push:
    branches:
      - main
  workflow_dispatch:

# 必须确保有写入权限
permissions:
  deployments: write
  contents: read

jobs:
  delete-history:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all deployments
        uses: strumwolf/delete-deployment-environment@v3
        with:
          # 使用内置的 token
          token: ${{ secrets.GITHUB_TOKEN }}
          # 这里的 environment 通常是 github-pages
          environment: github-pages
          # 只删除部署记录，不删除环境本身
          only_remove_deployments: true
